# Fake loading screen

image loading_1 = "gui/loading/loading_1.jpg"
image loading_2 = "gui/loading/loading_2.jpg"
image loading_3 = "gui/loading/loading_3.jpg"
image loading_4 = "gui/loading/loading_4.jpg"
image loading_5 = "gui/loading/loading_5.jpg"
image loading_6 = "gui/loading/loading_6.jpg"
image loadinglvl0 = "gui/loadinglvl/loadinglvl0.png"
image loadinglvl1 = "gui/loadinglvl/loadinglvl1.png"
image loadinglvl2 = "gui/loadinglvl/loadinglvl2.png"
image loadinglvl3 = "gui/loadinglvl/loadinglvl3.png"
image loadinglvl4 = "gui/loadinglvl/loadinglvl4.png"
image loadinglvl5 = "gui/loadinglvl/loadinglvl5.png"
image loadinglvl6 = "gui/loadinglvl/loadinglvl6.png"
image bg_r1m1load = "gui/loadinglvl/splashes/bg_r1m1load.png"
image bg_r1m2load = "gui/loadinglvl/splashes/bg_r1m2load.png"
image bg_r1m3load = "gui/loadinglvl/splashes/bg_r1m3load.png"
image bg_r1m4load = "gui/loadinglvl/splashes/bg_r1m4load.png"

# Backgrounds: r1m1

image bg_afterfdeath = "images/bgs/r1m1/bg_afterfdeath.jpg"
image bg_caniride = "images/bgs/r1m1/bg_caniride.jpg"
image bg_dyingfather = "images/bgs/r1m1/bg_dyingfather.jpg"
image bg_fatherdead = "images/bgs/r1m1/bg_fatherdead.jpg"
image bg_felba_hornet = "images/bgs/r1m1/bg_felba_hornet.jpg"
image bg_felix = "images/bgs/r1m1/bg_felix.jpg"
image bg_felixbase = "images/bgs/r1m1/bg_felixbase.jpg"
image bg_felixbaseeasy = "images/bgs/r1m1/bg_felixbaseeasy.jpg"
image bg_felixbasestorm = "images/bgs/r1m1/bg_felixbasestorm.jpg"
image bg_felixdefeat = "images/bgs/r1m1/bg_felixdefeat.jpg"
image bg_felixdlg = "images/bgs/r1m1/bg_felixdlg.jpg"
image bg_felixfail = "images/bgs/r1m1/bg_felixfail.jpg"
image bg_felixfight = "images/bgs/r1m1/bg_felixfight.jpg"
image bg_felixrun = "images/bgs/r1m1/bg_felixrun.jpg"
image bg_felix_nocars = "images/bgs/r1m1/bg_felix_nocars.jpg"
image bg_firstenemy = "images/bgs/r1m1/bg_firstenemy.jpg"
image bg_glburnaway = "images/bgs/r1m1/bg_glburnaway.jpg"
image bg_glburning = "images/bgs/r1m1/bg_glburning.jpg"
image bg_glukhoe = "images/bgs/r1m1/bg_glukhoe.jpg"
image bg_gugulino = "images/bgs/r1m1/bg_gugulino.jpg"
image bg_insowth = "images/bgs/r1m1/bg_insowth.jpg"
image bg_secenemy = "images/bgs/r1m1/bg_secenemy.jpg"
image bg_sowth = "images/bgs/r1m1/bg_sowth.jpg"
image bg_tosowth = "images/bgs/r1m1/bg_tosowth.jpg"
image bg_troitckoe = "images/bgs/r1m1/bg_troitckoe.jpg"
image bg_whatiffelix = "images/bgs/r1m1/bg_whatiffelix.jpg"
image bg_zaimka = "images/bgs/r1m1/bg_zaimka.jpg"
image bg_zapravka = "images/bgs/r1m1/bg_zapravka.jpg"
image bg_firsteverenemy = "images/bgs/r1m1/bg_firsteverenemy.jpg"
image bg_secondenemy = "images/bgs/r1m1/bg_secondenemy.jpg"

# Backgrounds: r1m2

image bg_ben = "images/bgs/r1m2/bg_ben.jpg"
image bg_ben1 = "images/bgs/r1m2/bg_ben1.jpg"
image bg_fightforloot = "images/bgs/r1m2/bg_fightforloot.jpg"
image bg_locus = "images/bgs/r1m2/bg_locus.jpg"
image bg_loot = "images/bgs/r1m2/bg_loot.jpg"
image bg_midgard = "images/bgs/r1m2/bg_midgard.jpg"
image bg_porto = "images/bgs/r1m2/bg_porto.jpg"
image bg_razvyazka = "images/bgs/r1m2/bg_razvyazka.jpg"
image bg_ridzin = "images/bgs/r1m2/bg_ridzin.jpg"
image bg_toporto = "images/bgs/r1m2/bg_toporto.jpg"
image bg_toportoe1 = "images/bgs/r1m2/bg_toportoe1.jpg"
image bg_vostochnoe = "images/bgs/r1m2/bg_vostochnoe.jpg"
image bg_lisarescue = "images/bgs/r1m2/bg_lisarescue.jpg"
image bg_lisarescue1_van = "images/bgs/r1m2/bg_lisarescue1_van.jpg"
image bg_lisarescue1_ml = "images/bgs/r1m2/bg_lisarescue1_ml.jpg"
image bg_lisarescue2 = "images/bgs/r1m2/bg_lisarescue2.jpg"
image bg_lisarescue_fight = "images/bgs/r1m2/bg_lisarescue_fight.jpg"

# Backgrounds: r1m2 - Lisa Rescued

image bg_lr_1_Molokovoz_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_1_Molokovoz_Hornet.jpg"
image bg_lr_1_Molokovoz_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_1_Molokovoz_Kord.jpg"
image bg_lr_1_Molokovoz_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_1_Molokovoz_PKT.jpg"
image bg_lr_1_Molokovoz_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_1_Molokovoz_Specter.jpg"
image bg_lr_1_Molokovoz_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_1_Molokovoz_Storm.jpg"
image bg_lr_1_Van_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_1_Van_Hornet.jpg"
image bg_lr_1_Van_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_1_Van_Kord.jpg"
image bg_lr_1_Van_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_1_Van_PKT.jpg"
image bg_lr_1_Van_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_1_Van_Specter.jpg"
image bg_lr_1_Van_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_1_Van_Storm.jpg"
image bg_lr_2_Molokovoz_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_2_Molokovoz_Hornet.jpg"
image bg_lr_2_Molokovoz_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_2_Molokovoz_Kord.jpg"
image bg_lr_2_Molokovoz_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_2_Molokovoz_PKT.jpg"
image bg_lr_2_Molokovoz_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_2_Molokovoz_Specter.jpg"
image bg_lr_2_Molokovoz_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_2_Molokovoz_Storm.jpg"
image bg_lr_2_Van_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_2_Van_Hornet.jpg"
image bg_lr_2_Van_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_2_Van_Kord.jpg"
image bg_lr_2_Van_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_2_Van_PKT.jpg"
image bg_lr_2_Van_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_2_Van_Specter.jpg"
image bg_lr_2_Van_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_2_Van_Storm.jpg"
image bg_lr_3_Molokovoz_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_3_Molokovoz_Hornet.jpg"
image bg_lr_3_Molokovoz_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_3_Molokovoz_Kord.jpg"
image bg_lr_3_Molokovoz_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_3_Molokovoz_PKT.jpg"
image bg_lr_3_Molokovoz_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_3_Molokovoz_Specter.jpg"
image bg_lr_3_Molokovoz_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_3_Molokovoz_Storm.jpg"
image bg_lr_3_Van_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_3_Van_Hornet.jpg"
image bg_lr_3_Van_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_3_Van_Kord.jpg"
image bg_lr_3_Van_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_3_Van_PKT.jpg"
image bg_lr_3_Van_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_3_Van_Specter.jpg"
image bg_lr_3_Van_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_3_Van_Storm.jpg"
image bg_lr_4_Molokovoz_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_4_Molokovoz_Hornet.jpg"
image bg_lr_4_Molokovoz_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_4_Molokovoz_Kord.jpg"
image bg_lr_4_Molokovoz_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_4_Molokovoz_PKT.jpg"
image bg_lr_4_Molokovoz_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_4_Molokovoz_Specter.jpg"
image bg_lr_4_Molokovoz_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_4_Molokovoz_Storm.jpg"
image bg_lr_4_Van_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_4_Van_Hornet.jpg"
image bg_lr_4_Van_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_4_Van_Kord.jpg"
image bg_lr_4_Van_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_4_Van_PKT.jpg"
image bg_lr_4_Van_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_4_Van_Specter.jpg"
image bg_lr_4_Van_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_4_Van_Storm.jpg"
image bg_lr_5_Molokovoz_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_5_Molokovoz_Hornet.jpg"
image bg_lr_5_Molokovoz_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_5_Molokovoz_Kord.jpg"
image bg_lr_5_Molokovoz_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_5_Molokovoz_PKT.jpg"
image bg_lr_5_Molokovoz_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_5_Molokovoz_Specter.jpg"
image bg_lr_5_Molokovoz_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_5_Molokovoz_Storm.jpg"
image bg_lr_5_Van_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_5_Van_Hornet.jpg"
image bg_lr_5_Van_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_5_Van_Kord.jpg"
image bg_lr_5_Van_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_5_Van_PKT.jpg"
image bg_lr_5_Van_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_5_Van_Specter.jpg"
image bg_lr_5_Van_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_5_Van_Storm.jpg"
image bg_lr_6_Molokovoz_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_6_Molokovoz_Hornet.jpg"
image bg_lr_6_Molokovoz_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_6_Molokovoz_Kord.jpg"
image bg_lr_6_Molokovoz_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_6_Molokovoz_PKT.jpg"
image bg_lr_6_Molokovoz_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_6_Molokovoz_Specter.jpg"
image bg_lr_6_Molokovoz_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_6_Molokovoz_Storm.jpg"
image bg_lr_6_Van_Hornet = "images/bgs/r1m2/LisaRescued/bg_lr_6_Van_Hornet.jpg"
image bg_lr_6_Van_Kord = "images/bgs/r1m2/LisaRescued/bg_lr_6_Van_Kord.jpg"
image bg_lr_6_Van_PKT = "images/bgs/r1m2/LisaRescued/bg_lr_6_Van_PKT.jpg"
image bg_lr_6_Van_Specter = "images/bgs/r1m2/LisaRescued/bg_lr_6_Van_Specter.jpg"
image bg_lr_6_Van_Storm = "images/bgs/r1m2/LisaRescued/bg_lr_6_Van_Storm.jpg"

# Backgrounds: r1m3

image bg_aivenhouse = "images/bgs/r1m3/bg_aivenhouse.jpg"
image bg_asgard = "images/bgs/r1m3/bg_asgard.jpg"
image bg_bandbridge = "images/bgs/r1m3/bg_bandbridge.jpg"
image bg_bandbridge_down = "images/bgs/r1m3/bg_bandbridge_down.jpg"
image bg_benradio = "images/bgs/r1m3/bg_benradio.jpg"
image bg_m3nolisa = "images/bgs/r1m3/bg_m3nolisa.jpg"
image bg_minin = "images/bgs/r1m3/bg_minin.jpg"
image bg_mvillage = "images/bgs/r1m3/bg_mvillage.jpg"
image bg_mvillage_fight = "images/bgs/r1m3/bg_mvillage_fight.jpg"
image bg_nearbridge = "images/bgs/r1m3/bg_nearbridge.jpg"
image bg_nearbridgeenemy = "images/bgs/r1m3/bg_nearbridgeenemy.jpg"
image bg_oil = "images/bgs/r1m3/bg_oil.jpg"
image bg_oilenemy = "images/bgs/r1m3/bg_oilenemy.jpg"
image bg_pesht = "images/bgs/r1m3/bg_pesht.jpg"
image bg_oillastenemy = "images/bgs/r1m3/bg_oillastenemy.jpg"
image bg_oilspy_1 = "images/bgs/r1m3/bg_oilspy_1.jpg"
image bg_oilspy_2 = "images/bgs/r1m3/bg_oilspy_2.jpg"
image bg_oilspy_3 = "images/bgs/r1m3/bg_oilspy_3.jpg"
image bg_oilspy_fight = "images/bgs/r1m3/bg_oilspy_fight.jpg"
image bg_spymer_1 = "images/bgs/r1m3/bg_spymer_1.jpg"
image bg_spymer_2 = "images/bgs/r1m3/bg_spymer_2.jpg"
image bg_spymer_3 = "images/bgs/r1m3/bg_spymer_3.jpg"
image bg_spymer_4 = "images/bgs/r1m3/bg_spymer_4.jpg"
image bg_spymer_5 = "images/bgs/r1m3/bg_spymer_5.jpg"
image bg_spymer_6 = "images/bgs/r1m3/bg_spymer_6.jpg"
image bg_base51 = "images/bgs/r1m3/bg_base51.jpg"
image bg_base51fight = "images/bgs/r1m3/bg_base51fight.jpg"
image bg_tunnel = "images/bgs/r1m3/bg_tunnel.jpg"
image bg_tunnelhide_1 = "images/bgs/r1m3/bg_tunnelhide_1.jpg"
image bg_tunnelhide_2 = "images/bgs/r1m3/bg_tunnelhide_2.jpg"
image bg_tunnelhide_3 = "images/bgs/r1m3/bg_tunnelhide_3.jpg"
image bg_tunnelhide_4 = "images/bgs/r1m3/bg_tunnelhide_4.jpg"
image bg_fightforkey = "images/bgs/r1m3/bg_fightforkey.jpg"
image bg_followkeyman_1 = "images/bgs/r1m3/bg_followkeyman_1.jpg"
image bg_followkeyman_2 = "images/bgs/r1m3/bg_followkeyman_2.jpg"
image bg_followkeyman_3 = "images/bgs/r1m3/bg_followkeyman_3.jpg"
image bg_followkeyman_4 = "images/bgs/r1m3/bg_followkeyman_4.jpg"

# Backgrounds: r1m4

image bg_helfirst = "images/bgs/r1m4/bg_helfirst.jpg"
image bg_olm = "images/bgs/r1m4/bg_olm.jpg"
image bg_saliniom = "images/bgs/r1m4/bg_saliniom.jpg"
image bg_lauka = "images/bgs/r1m4/bg_lauka.jpg"
image bg_kalis = "images/bgs/r1m4/bg_kalis.jpg"
image bg_kordan = "images/bgs/r1m4/bg_kordan.jpg"
image bg_boloto = "images/bgs/r1m4/bg_boloto.jpg"
image bg_boloto_1 = "images/bgs/r1m4/bg_boloto_1.jpg"
image bg_boloto_2 = "images/bgs/r1m4/bg_boloto_2.jpg"
image bg_kran = "images/bgs/r1m4/bg_kran.jpg"
image bg_kranfight = "images/bgs/r1m4/bg_kranfight.jpg"
image bg_bosskran_dead = "images/bgs/r1m4/bg_bosskran_dead.jpg"
image bg_leaver1_cargo1_1 = "images/bgs/r1m4/bg_leaver1_cargo1_1.jpg"
image bg_leaver1_cargo1_2 = "images/bgs/r1m4/bg_leaver1_cargo1_2.jpg"
image bg_leaver1_cargo1_3 = "images/bgs/r1m4/bg_leaver1_cargo1_3.jpg"
image bg_leaver1_cargo1_4 = "images/bgs/r1m4/bg_leaver1_cargo1_4.jpg"
image bg_leaver1_cargo3_1 = "images/bgs/r1m4/bg_leaver1_cargo3_1.jpg"
image bg_leaver1_cargo3_2 = "images/bgs/r1m4/bg_leaver1_cargo3_2.jpg"
image bg_leaver1_cargo3_3 = "images/bgs/r1m4/bg_leaver1_cargo3_3.jpg"
image bg_leaver1_cargo3_4 = "images/bgs/r1m4/bg_leaver1_cargo3_4.jpg"
image bg_warehouse = "images/bgs/r1m4/bg_warehouse.jpg"
image bg_freeleader = "images/bgs/r1m4/bg_freeleader.jpg"
image bg_freeleader_1 = "images/bgs/r1m4/bg_freeleader_1.jpg"
image bg_freeleader_2 = "images/bgs/r1m4/bg_freeleader_2.jpg"
image bg_freeleaderfight = "images/bgs/r1m4/bg_freeleaderfight.jpg"
image bg_leaderisfree = "images/bgs/r1m4/bg_leaderisfree.jpg"
image bg_leaver1_van_1 = "images/bgs/r1m4/bg_leaver1_van_1.jpg"
image bg_leaver1_van_2 = "images/bgs/r1m4/bg_leaver1_van_2.jpg"
image bg_leaver1_van_3 = "images/bgs/r1m4/bg_leaver1_van_3.jpg"
image bg_leaver1_van_4 = "images/bgs/r1m4/bg_leaver1_van_4.jpg"
image bg_leaver1_ural_1 = "images/bgs/r1m4/bg_leaver1_ural_1.jpg"
image bg_leaver1_ural_2 = "images/bgs/r1m4/bg_leaver1_ural_2.jpg"
image bg_leaver1_ural_3 = "images/bgs/r1m4/bg_leaver1_ural_3.jpg"
image bg_leaver1_ural_4 = "images/bgs/r1m4/bg_leaver1_ural_4.jpg"

# Sprites: Characters

image ben1 = "images/sprites/chr/ben1.png"
image ben2 = "images/sprites/chr/ben2.png"
image ben3 = "images/sprites/chr/ben3.png"
image dronn = "images/sprites/chr/dronn.png"
image farmerdi = "images/sprites/chr/farmerdi.png"
image felix = "images/sprites/chr/felix.png"
image felix2 = "images/sprites/chr/felix2.png"
image fther = "images/sprites/chr/fther.png"
image fther2 = "images/sprites/chr/fther2.png"
image hose = "images/sprites/chr/hose.png"
image kventin = "images/sprites/chr/kventin.png"
image lisa = "images/sprites/chr/lisa.png"
image lisa2 = "images/sprites/chr/lisa2.png"
image mc3 = "images/sprites/chr/mc3.png"
image mc4 = "images/sprites/chr/mc4.png"
image mc5 = "images/sprites/chr/mc5.png"
image mc6 = "images/sprites/chr/mc6.png"
image mchar = "images/sprites/chr/mchar.png"
image mcsurp = "images/sprites/chr/mcsurp.png"
image mc_2 = "images/sprites/chr/mc_2.png"
image oldwoman = "images/sprites/chr/oldwoman.png"
image scientist = "images/sprites/chr/scientist.png"
image sergo = "images/sprites/chr/sergo.png"
image sergo2 = "images/sprites/chr/sergo2.png"
image sergo3 = "images/sprites/chr/sergo3.png"
image shon = "images/sprites/chr/shon.png"
image zavhoz = "images/sprites/chr/zavhoz.png"
image pguard = "images/sprites/chr/pguard.png"
image seller = "images/sprites/chr/seller.png"
image mworker = "images/sprites/chr/mworker.png"
image mcback = "images/sprites/chr/mcback.png"
image mc4_key = "images/sprites/chr/mc4_key.png"
image mimayor = "images/sprites/chr/mayor.png"
image OilMineWorker = "images/sprites/chr/OilMineWorker.png"
image MininWorker2 = "images/sprites/chr/MininWorker2.png"
image olmeper = "images/sprites/chr/olmeper.png"
image matvey = "images/sprites/chr/matvey.png"
image homer = "images/sprites/chr/homer.png"
image mc7 = "images/sprites/chr/mc7.png"
image galden = "images/sprites/chr/galden.png"
image wsecurity = "images/sprites/chr/wsecurity.png"
image bobbase51 = "images/sprites/chr/bob.png"
image kane = "images/sprites/chr/kane.png"
image pablo = "images/sprites/chr/pablo.png"
image tunnelguy = "images/sprites/chr/tunnelguy.png"

# Sprites: Enemy's

image firsteverenemy = "images/sprites/enemy/firsteverenemy.png"
image secenemy = "images/sprites/enemy/secenemy.png"
image felixcar = "images/sprites/enemy/felixcar.png"
image felixteam = "images/sprites/enemy/felixteam.png"
image lootdefender = "images/sprites/enemy/lootdefender.png"
image to_porto_e1 = "images/sprites/enemy/to_porto_e1.png"
image brigde_defender = "images/sprites/enemy/brigde_defender.png"
image minerattackers = "images/sprites/enemy/minerattackers.png"
image oilbandits = "images/sprites/enemy/oilbandits.png"
image base51fight = "images/sprites/enemy/base51fight.png"
image keyholder = "images/sprites/enemy/keyholder.png"

image randomenemy1 = "images/sprites/enemy/randomenemy1.png"
image randomenemy2 = "images/sprites/enemy/randomenemy2.png"
image randomenemy3 = "images/sprites/enemy/randomenemy3.png"
image randomenemy4 = "images/sprites/enemy/randomenemy4.png"

# Tutorial

image tr_fight = "images/tutorial/tr_fight.jpg"
image tr_fight_hp = "images/tutorial/tr_fight_hp.jpg"
image tr_fight_heal = "images/tutorial/tr_fight_heal.jpg"
image tr_fight_action = "images/tutorial/tr_fight_action.jpg"
image tr_fight_enemyhp = "images/tutorial/tr_fight_enemyhp.jpg"
image tr_fight_healbtn = "images/tutorial/tr_fight_healbtn.jpg"
image tr_fight_attack = "images/tutorial/tr_fight_attack.jpg"
image tr_townmenu = "images/tutorial/tr_townmenu.jpg"
image tr_townmenu_statsbtn = "images/tutorial/tr_townmenu_statsbtn.jpg"
image tr_townmenu_stats = "images/tutorial/tr_townmenu_stats.jpg"
image tr_townmenu_inventorybtn = "images/tutorial/tr_townmenu_inventorybtn.jpg"
image tr_townmenu_inventory = "images/tutorial/tr_townmenu_inventory.jpg"
image tr_townmenu_stats_invbutton = "images/tutorial/tr_townmenu_stats_invbutton.jpg"
image tr_townmenu_inventory_gunsel = "images/tutorial/tr_townmenu_inventory_gunsel.jpg"
image tr_townmenu_carshopbtn = "images/tutorial/tr_townmenu_carshopbtn.jpg"
image tr_carshop = "images/tutorial/tr_carshop.jpg"
image tr_townmenu_gunshopbtn = "images/tutorial/tr_townmenu_gunshopbtn.jpg"
image tr_townmenu_gunshop = "images/tutorial/tr_townmenu_gunshop.jpg"
image tr_townmenu_gunshop_desc = "images/tutorial/tr_townmenu_gunshop_desc.jpg"
image tr_townmenu_village = "images/tutorial/tr_townmenu_village.jpg"
image tr_checkpoints = "images/tutorial/tr_checkpoints.jpg"
image tr_carshop_carlist = "images/tutorial/tr_carshop_carlist.jpg"
image tr_carshop_hp_heal = "images/tutorial/tr_carshop_hp_heal.jpg"
image tr_carshop_buybtn = "images/tutorial/tr_carshop_buybtn.jpg"
image tr_carshop_fixbtn = "images/tutorial/tr_carshop_fixbtn.jpg"
image tr_carshop_buyhealbtn = "images/tutorial/tr_carshop_buyhealbtn.jpg"
image tr_carshop_stats = "images/tutorial/tr_carshop_stats.jpg"
image tr_carshop_desc = "images/tutorial/tr_carshop_desc.jpg"

# Effects

image damage = "images/effects/damage.png"

image mainmenu_loop = Movie(play="movies/mainmenu_loop1.avi")

image scrach_anim_24fps:
    blend "multiply"
    "gui/scratch/scrach00.png"
    pause 0.0667
    "gui/scratch/scrach01.png"
    pause 0.0667
    "gui/scratch/scrach02.png"
    pause 0.0667
    "gui/scratch/scrach03.png"
    pause 0.0667
    "gui/scratch/scrach04.png"
    pause 0.0667
    "gui/scratch/scrach05.png"
    pause 0.0667
    "gui/scratch/scrach06.png"
    pause 0.0667
    "gui/scratch/scrach07.png"
    pause 0.0667
    "gui/scratch/scrach08.png"
    pause 0.0667
    "gui/scratch/scrach09.png"
    pause 0.0667
    "gui/scratch/scrach10.png"
    pause 0.0667
    "gui/scratch/scrach11.png"
    pause 0.0667
    repeat